### ISSUE TITLE
Default Photos Format

### ISSUE THREAD

**Issue by yeqbfgxjiq** [aracred/tokeneconomics#3]
Session 1 and 2 photos are in JPG, but [session 3 photos](https://github.com/aracred/cryptoeconomics/tree/master/session3) are in HEIC. Not that big of a deal, but it would be good to have a standard format for all photos in the repo. @mzargham is there a reason we switched from JPG to HEIC and/or which format do you recommend moving forward?

**Comment by mzargham** [comment]
I think i switched which app i used to capture them. HEIC is kind of a pain, let me see about making them all JPG

**Comment by yeqbfgxjiq** [comment]
Resolved via latest worksession. Thanks!
